export const TEXTS = [
  "Il cielo notturno è costellato di stelle che brillano come diamanti. Ogni punto luminoso racconta una storia antica, un viaggio di luce durato milioni di anni. Guardare verso l'alto ci ricorda quanto siamo piccoli nell'universo.",
  "La tecnologia ha trasformato il modo in cui viviamo e lavoriamo. I computer sono diventati strumenti indispensabili per la comunicazione, la creatività e la produttività. Il futuro digitale è già presente nella nostra quotidianità.",
  "La natura offre spettacoli meravigliosi in ogni stagione. In primavera i fiori colorano i prati, d'estate il sole scalda la terra, in autunno le foglie cadono danzando nel vento, e in inverno la neve copre ogni cosa di bianco.",
  "La musica è un linguaggio universale che supera le barriere culturali e geografiche. Una melodia può evocare ricordi lontani, suscitare emozioni profonde e unire persone di culture diverse in un momento di condivisione.",
  "Leggere è una delle attività più arricchenti che un essere umano possa praticare. Ogni libro apre una finestra su mondi nuovi, amplia la nostra comprensione della realtà e stimola l'immaginazione in modi sorprendenti.",
];

export const KEYBOARD_ROWS = [
  [
    { l: "`", s: "~", c: "Backquote" },
    { l: "1", s: "!", c: "Digit1" },
    { l: "2", s: '"', c: "Digit2" },
    { l: "3", s: "£", c: "Digit3" },
    { l: "4", s: "$", c: "Digit4" },
    { l: "5", s: "%", c: "Digit5" },
    { l: "6", s: "&", c: "Digit6" },
    { l: "7", s: "/", c: "Digit7" },
    { l: "8", s: "(", c: "Digit8" },
    { l: "9", s: ")", c: "Digit9" },
    { l: "0", s: "=", c: "Digit0" },
    { l: "'", s: "?", c: "Minus" },
    { l: "ì", s: "^", c: "Equal" },
    { l: "←", c: "Backspace", w: "w20", sp: true },
  ],
  [
    { l: "Tab", c: "Tab", w: "w15", sp: true },
    { l: "q", s: "Q", c: "KeyQ" },
    { l: "w", s: "W", c: "KeyW" },
    { l: "e", s: "E", c: "KeyE" },
    { l: "r", s: "R", c: "KeyR" },
    { l: "t", s: "T", c: "KeyT" },
    { l: "y", s: "Y", c: "KeyY" },
    { l: "u", s: "U", c: "KeyU" },
    { l: "i", s: "I", c: "KeyI" },
    { l: "o", s: "O", c: "KeyO" },
    { l: "p", s: "P", c: "KeyP" },
    { l: "è", s: "é", c: "BracketLeft" },
    { l: "+", s: "*", c: "BracketRight" },
    { l: "↵", c: "Enter", w: "w20", sp: true },
  ],
  [
    { l: "Caps", c: "CapsLock", w: "w20", sp: true },
    { l: "a", s: "A", c: "KeyA" },
    { l: "s", s: "S", c: "KeyS" },
    { l: "d", s: "D", c: "KeyD" },
    { l: "f", s: "F", c: "KeyF" },
    { l: "g", s: "G", c: "KeyG" },
    { l: "h", s: "H", c: "KeyH" },
    { l: "j", s: "J", c: "KeyJ" },
    { l: "k", s: "K", c: "KeyK" },
    { l: "l", s: "L", c: "KeyL" },
    { l: "ò", s: "ç", c: "Semicolon" },
    { l: "à", s: "°", c: "Quote" },
    { l: "ù", s: "§", c: "Backslash" },
  ],
  [
    { l: "Shift", c: "ShiftLeft", w: "w25", sp: true },
    { l: "z", s: "Z", c: "KeyZ" },
    { l: "x", s: "X", c: "KeyX" },
    { l: "c", s: "C", c: "KeyC" },
    { l: "v", s: "V", c: "KeyV" },
    { l: "b", s: "B", c: "KeyB" },
    { l: "n", s: "N", c: "KeyN" },
    { l: "m", s: "M", c: "KeyM" },
    { l: ",", s: ";", c: "Comma" },
    { l: ".", s: ":", c: "Period" },
    { l: "-", s: "_", c: "Slash" },
    { l: "Shift", c: "ShiftRight", w: "w25", sp: true },
  ],
  [
    { l: "Ctrl", c: "ControlLeft", w: "w15", sp: true },
    { l: "Alt", c: "AltLeft", w: "w15", sp: true },
    { l: "", c: "Space", w: "wsp" },
    { l: "Alt", c: "AltRight", w: "w15", sp: true },
    { l: "Ctrl", c: "ControlRight", w: "w15", sp: true },
  ],
];
